export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT'
export const INIT_BURGER = 'INIT_BURGER'
export const START_BURGER = 'START_BURGER'
export const BURGER_FAILED = 'BURGER_FAILED'
export const LOADING = 'LOADING'

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START' 
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS' 
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL' 
export const PURCHASE_INIT = 'PURCHASE_INIT'

export const FETCH_ORDERS = 'FETCH_ORDERS'
export const FETCH_ORDERS_START = 'FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL'
export const DELETE_ORDER = 'DELETE_ORDER' 
export const DELETE_ORDER_ON_SERVER = 'DELETE_ORDER_ON_SERVER' 

export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

export const SET_AUTH_INITIALIZED = 'SET_AUTH_INITIALIZED'
